# Generated by Django 5.2.7 on 2025-11-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_stanowsisko_osoba'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stanowsisko',
            new_name='Stanowisko',
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
